models:
  300M:
    n_layers: 16
    n_heads: 16
    d_model: 1024
    d_ff: 4096
    vocab_size: 50257
    max_seq_len: 4096
  1B:
    n_layers: 24
    n_heads: 24
    d_model: 1536
    d_ff: 6144
    vocab_size: 50257
    max_seq_len: 4096
  3B:
    n_layers: 36
    n_heads: 36
    d_model: 2048
    d_ff: 8192
    vocab_size: 50257
    max_seq_len: 8192

